export interface SeedCompany {
  name: string;
  industry: string;
  city: string;
  country: string;
  coords: [number, number];
  website: string;
  revenue: string;
  risk: number;
  employees: string;
  growth: string;
  reputation: string;
  details: string;
  news: string;
  ceo: string;
  founded: string;
  marketCap: string;
  healthIndex: number;
  type?: 'corp' | 'supplier' | 'competitor' | 'customer' | 'logistics' | 'subsidiary' | 'investor' | 'warehouse' | 'port' | 'airport' | 'factory' | 'office';
  category?: string;
  status?: string;
  suppliers?: string[];
  competitors?: string[];
  partners?: string[];
  customers?: string[];
  warehouses?: string[];
  factories?: string[];
  offices?: string[];
  ports?: string[];
  airports?: string[];
}

export const SEED_COMPANIES: SeedCompany[] = [
  // 1-10: Technology
  {
    name: "Apple Inc.",
    industry: "Technology",
    city: "Cupertino",
    country: "USA",
    coords: [37.33182, -122.03118],
    website: "https://apple.com",
    revenue: "$383B",
    risk: 8.5,
    employees: "164,000",
    growth: "+6.2%",
    reputation: "94/100",
    details: "Planetary technology leader specializing in premium hardware architectures and neural edge chipsets.",
    news: "Apple launches custom neural core accelerators for real-time edge processing.",
    ceo: "Tim Cook",
    founded: "1976",
    marketCap: "$3.35T",
    healthIndex: 94,
    status: "Verified Twin",
    suppliers: ["TSMC Co.", "Foxconn Shenzhen", "Sino Logistics"],
    competitors: ["Google LLC", "Microsoft Corporation", "Samsung Electronics"],
    partners: ["Infosys Ltd.", "DHL Supply Chain"],
    customers: ["Client Consumers", "Enterprise Clients"],
    warehouses: ["Chicago Distribution Hub"],
    factories: ["Foxconn Shenzhen"],
    offices: ["Apple London Office"]
  },
  {
    name: "Microsoft Corporation",
    industry: "Technology",
    city: "Redmond",
    country: "USA",
    coords: [47.674, -122.1215],
    website: "https://microsoft.com",
    revenue: "$245B",
    risk: 6.5,
    employees: "220,000",
    growth: "+12.4%",
    reputation: "95/100",
    details: "Hyperscale cloud, enterprise productivity solutions, and AI infrastructure pioneer.",
    news: "Microsoft expands Azure compute clusters across European green energy grids.",
    ceo: "Satya Nadella",
    founded: "1975",
    marketCap: "$3.20T",
    healthIndex: 95,
    status: "Verified Twin",
    suppliers: ["ASML Semiconductors", "Sino Logistics", "TSMC Co."],
    competitors: ["Google LLC", "Apple Inc.", "Amazon Retail"],
    partners: ["Infosys Ltd.", "TCS Consultancy"],
    customers: ["Enterprise Clients", "Government Solutions"],
    warehouses: ["Seattle Logistics Hub"],
    factories: ["Silicon Valley Fab"],
    offices: ["Microsoft Tokyo Office"]
  },
  {
    name: "Google LLC",
    industry: "Technology",
    city: "Mountain View",
    country: "USA",
    coords: [37.422, -122.084],
    website: "https://google.com",
    revenue: "$307B",
    risk: 7.2,
    employees: "182,000",
    growth: "+9.8%",
    reputation: "91/100",
    details: "Global search infrastructure, advertising systems, and cloud compute platform pioneer.",
    news: "Google initiates deployment of subsea fiber links between Tokyo and Singapore hubs.",
    ceo: "Sundar Pichai",
    founded: "1998",
    marketCap: "$2.15T",
    healthIndex: 91,
    status: "Verified Twin",
    suppliers: ["TSMC Co.", "Intel Corp"],
    competitors: ["Microsoft Corporation", "Meta Platforms", "Amazon Retail"],
    partners: ["Tesla Motors", "Infosys Ltd."],
    customers: ["Client Consumers", "Enterprise Clients"],
    offices: ["Google Zurich HQ"]
  },
  {
    name: "Meta Platforms",
    industry: "Technology",
    city: "Menlo Park",
    country: "USA",
    coords: [37.485, -122.148],
    website: "https://meta.com",
    revenue: "$134B",
    risk: 15.4,
    employees: "67,000",
    growth: "+15.8%",
    reputation: "81/100",
    details: "Social computing ecosystems, augmented architectures, and foundational open models creator.",
    news: "Meta deploys Llama-4 neural meshes across active data facility grids.",
    ceo: "Mark Zuckerberg",
    founded: "2004",
    marketCap: "$1.28T",
    healthIndex: 81,
    status: "Verified Twin",
    suppliers: ["NVIDIA Corp", "Intel Corp"],
    competitors: ["Google LLC", "TikTok ByteDance"],
    partners: ["Microsoft Corporation"],
    customers: ["Client Consumers"]
  },
  {
    name: "NVIDIA Corp",
    industry: "Technology",
    city: "Santa Clara",
    country: "USA",
    coords: [37.354, -121.955],
    website: "https://nvidia.com",
    revenue: "$60B",
    risk: 11.2,
    employees: "29,000",
    growth: "+125.6%",
    reputation: "93/100",
    details: "Pioneering accelerated graphics accelerators and AI architecture clusters.",
    news: "NVIDIA announces Blackwell chip shipments to global hyperscaler facilities.",
    ceo: "Jensen Huang",
    founded: "1993",
    marketCap: "$2.98T",
    healthIndex: 93,
    status: "Verified Twin",
    suppliers: ["TSMC Co.", "ASML Semiconductors"],
    competitors: ["Intel Corp", "AMD Inc."],
    partners: ["Microsoft Corporation", "Google LLC"],
    customers: ["Tesla Motors", "Meta Platforms"],
    factories: ["Hsinchu Fab Operations"]
  },
  {
    name: "Infosys Ltd.",
    industry: "Technology",
    city: "Bengaluru",
    country: "India",
    coords: [12.972, 77.595],
    website: "https://infosys.com",
    revenue: "$18B",
    risk: 12.0,
    employees: "320,000",
    growth: "+9.1%",
    reputation: "89/100",
    details: "Global digital consulting services driving large-scale system modernization.",
    news: "Infosys opens new innovation hub in Dusseldorf focusing on industrial AI twins.",
    ceo: "Salil Parekh",
    founded: "1981",
    marketCap: "$85B",
    healthIndex: 89,
    status: "Verified Twin",
    suppliers: ["Microsoft Corporation", "Google Cloud", "AWS"],
    competitors: ["TCS Consultancy", "Accenture Solutions"],
    partners: ["Apple Inc.", "Microsoft Corporation"],
    customers: ["Enterprise Clients"],
    offices: ["Bengaluru Corporate Campus"]
  },
  {
    name: "TCS Consultancy",
    industry: "Technology",
    city: "Mumbai",
    country: "India",
    coords: [19.076, 72.877],
    website: "https://tcs.com",
    revenue: "$29B",
    risk: 9.8,
    employees: "608,000",
    growth: "+7.8%",
    reputation: "92/100",
    details: "Largest global IT consulting services provider offering cognitive automation.",
    news: "TCS signs $1.5B digital transformation deal with European logistics cluster.",
    ceo: "K. Krithivasan",
    founded: "1968",
    marketCap: "$145B",
    healthIndex: 92,
    status: "Verified Twin",
    suppliers: ["Microsoft Corporation", "Google Cloud"],
    competitors: ["Infosys Ltd.", "Cognizant Solutions"],
    partners: ["Intel Corp"],
    customers: ["Enterprise Clients"]
  },
  {
    name: "TSMC Co.",
    industry: "Technology",
    city: "Hsinchu",
    country: "Taiwan",
    coords: [24.781, 120.993],
    website: "https://tsmc.com",
    revenue: "$70B",
    risk: 19.5,
    employees: "73,000",
    growth: "+16.2%",
    reputation: "96/100",
    details: "The world's largest dedicated independent semiconductor foundry group.",
    news: "TSMC begins pilot production on next-generation sub-2nm node processes.",
    ceo: "C.C. Wei",
    founded: "1887",
    marketCap: "$820B",
    healthIndex: 96,
    status: "Verified Twin",
    suppliers: ["ASML Semiconductors", "Apex Mining"],
    competitors: ["Samsung Electronics", "Intel Corp"],
    partners: ["NVIDIA Corp", "Apple Inc."],
    customers: ["Apple Inc.", "NVIDIA Corp"],
    factories: ["Hsinchu Fab 18"]
  },
  {
    name: "Samsung Electronics",
    industry: "Technology",
    city: "Suwon",
    country: "South Korea",
    coords: [37.263, 127.029],
    website: "https://samsung.com",
    revenue: "$200B",
    risk: 14.8,
    employees: "270,000",
    growth: "+4.1%",
    reputation: "88/100",
    details: "Consumer electronics giant and memory semiconductor market leader.",
    news: "Samsung announces breakthrough high-bandwidth memory chips validation.",
    ceo: "Jong-Hee Han",
    founded: "1969",
    marketCap: "$380B",
    healthIndex: 88,
    status: "Verified Twin",
    suppliers: ["ASML Semiconductors", "Sino Logistics"],
    competitors: ["Apple Inc.", "TSMC Co."],
    customers: ["Client Consumers", "NVIDIA Corp"],
    factories: ["Giheung Semiconductor Line"]
  },
  {
    name: "ASML Semiconductors",
    industry: "Technology",
    city: "Veldhoven",
    country: "Netherlands",
    coords: [51.408, 5.408],
    website: "https://asml.com",
    revenue: "$28B",
    risk: 12.6,
    employees: "42,000",
    growth: "+22.4%",
    reputation: "97/100",
    details: "Monopoly supplier of Extreme Ultraviolet (EUV) photolithography machines.",
    news: "ASML ships first High-NA EUV lithography system to USA research foundry.",
    ceo: "Christophe Fouquet",
    founded: "1984",
    marketCap: "$375B",
    healthIndex: 97,
    status: "Verified Twin",
    suppliers: ["Zeiss Optics", "Trumpf Laser"],
    competitors: ["Nikon Corp", "Canon Inc."],
    partners: ["TSMC Co.", "Samsung Electronics"],
    customers: ["TSMC Co.", "Samsung Electronics", "Intel Corp"],
    factories: ["Veldhoven Assembly Plant"]
  },

  // 11-20: Healthcare
  {
    name: "Pfizer Inc.",
    industry: "Healthcare",
    city: "New York",
    country: "USA",
    coords: [40.749, -73.974],
    website: "https://pfizer.com",
    revenue: "$58B",
    risk: 16.8,
    employees: "83,000",
    growth: "-2.4%",
    reputation: "85/100",
    details: "Global biopharmaceutical developer of dynamic genetic vaccine therapies.",
    news: "Pfizer initiates Phase 3 trial for combo mRNA flu-COVID inoculation.",
    ceo: "Albert Bourla",
    founded: "1849",
    marketCap: "$162B",
    healthIndex: 85,
    status: "Verified Twin",
    suppliers: ["Lonza Group", "Bormioli Glass"],
    competitors: ["Novartis Group", "Merck & Co."],
    partners: ["BioNTech SE"],
    customers: ["Government Solutions", "Healthcare Centers"],
    factories: ["Kalamazoo Bio-Facility"]
  },
  {
    name: "Johnson & Johnson",
    industry: "Healthcare",
    city: "New Brunswick",
    country: "USA",
    coords: [40.499, -74.444],
    website: "https://jnj.com",
    revenue: "$85B",
    risk: 9.4,
    employees: "152,000",
    growth: "+5.1%",
    reputation: "92/100",
    details: "Diversified healthcare giant leading medical devices and pharmaceutical therapies.",
    news: "J&J acquires robotics surgical interface startup to expand oncology systems.",
    ceo: "Joaquin Duato",
    founded: "1886",
    marketCap: "$380B",
    healthIndex: 92,
    status: "Verified Twin",
    suppliers: ["Sino Logistics", "West Pharmaceutics"],
    competitors: ["Pfizer Inc.", "Roche Group"],
    customers: ["Healthcare Centers"],
    offices: ["New Brunswick HQ"]
  },
  {
    name: "Roche Group",
    industry: "Healthcare",
    city: "Basel",
    country: "Switzerland",
    coords: [47.558, 7.587],
    website: "https://roche.com",
    revenue: "$63B",
    risk: 8.9,
    employees: "101,000",
    growth: "+3.2%",
    reputation: "94/100",
    details: "Global diagnostics and specialized biotechnology oncology treatment innovator.",
    news: "Roche launches targeted diagnostic assay test panel for neurological disorders.",
    ceo: "Thomas Schinecker",
    founded: "1896",
    marketCap: "$254B",
    healthIndex: 94,
    status: "Verified Twin",
    suppliers: ["Siegfried Holding", "Eppendorf AG"],
    competitors: ["Novartis Group", "Johnson & Johnson"],
    customers: ["Healthcare Centers", "Diagnostics Labs"],
    factories: ["Penzberg Biotech Site"]
  },
  {
    name: "Novartis Group",
    industry: "Healthcare",
    city: "Basel",
    country: "Switzerland",
    coords: [47.571, 7.564],
    website: "https://novartis.com",
    revenue: "$48B",
    risk: 10.1,
    employees: "76,000",
    growth: "+6.5%",
    reputation: "90/100",
    details: "Leader in innovative prescription drugs, gene therapies, and biosimilars.",
    news: "Novartis completes regulatory filing for advanced cardiovascular gene therapy.",
    ceo: "Vas Narasimhan",
    founded: "1996",
    marketCap: "$210B",
    healthIndex: 90,
    status: "Verified Twin",
    suppliers: ["Bachem AG", "Sino Logistics"],
    competitors: ["Roche Group", "Pfizer Inc."],
    customers: ["Healthcare Centers"]
  },
  {
    name: "Merck & Co.",
    industry: "Healthcare",
    city: "Rahway",
    country: "USA",
    coords: [40.663, -74.275],
    website: "https://merck.com",
    revenue: "$60B",
    risk: 11.5,
    employees: "72,000",
    growth: "+8.9%",
    reputation: "91/100",
    details: "Research-driven biopharmaceutical developer of blockbuster oncology immunotherapies.",
    news: "Merck expands manufacturing lines for Keytruda oncology vials in North Carolina.",
    ceo: "Robert Davis",
    founded: "1891",
    marketCap: "$278B",
    healthIndex: 91,
    status: "Verified Twin",
    suppliers: ["Lonza Group", "West Pharmaceutics"],
    competitors: ["Pfizer Inc.", "Bristol Myers Squibb"],
    customers: ["Healthcare Centers"]
  },
  {
    name: "Eli Lilly",
    industry: "Healthcare",
    city: "Indianapolis",
    country: "USA",
    coords: [39.761, -86.158],
    website: "https://lilly.com",
    revenue: "$34B",
    risk: 14.5,
    employees: "43,000",
    growth: "+28.4%",
    reputation: "94/100",
    details: "Pioneering clinical developers of metabolic and Alzheimer weight therapy solutions.",
    news: "Lilly secures approvals for expanded production of metabolic treatments in Ireland.",
    ceo: "David Ricks",
    founded: "1876",
    marketCap: "$710B",
    healthIndex: 94,
    status: "Verified Twin",
    suppliers: ["Siegfried Holding", "Lonza Group"],
    competitors: ["Novo Nordisk", "Pfizer Inc."],
    customers: ["Healthcare Centers"]
  },
  {
    name: "AstraZeneca",
    industry: "Healthcare",
    city: "Cambridge",
    country: "UK",
    coords: [52.193, 0.134],
    website: "https://astrazeneca.com",
    revenue: "$45B",
    risk: 12.2,
    employees: "89,000",
    growth: "+10.5%",
    reputation: "89/100",
    details: "Anglo-Swedish pharma leader focus on oncology, respiratory, and rare diseases.",
    news: "AstraZeneca invests $400m to construct carbon-neutral inhalation facility in UK.",
    ceo: "Pascal Soriot",
    founded: "1999",
    marketCap: "$198B",
    healthIndex: 89,
    status: "Verified Twin",
    suppliers: ["Bormioli Glass", "Sino Logistics"],
    competitors: ["GSK plc", "Pfizer Inc."],
    customers: ["Healthcare Centers"]
  },
  {
    name: "GSK plc",
    industry: "Healthcare",
    city: "London",
    country: "UK",
    coords: [51.488, -0.315],
    website: "https://gsk.com",
    revenue: "$38B",
    risk: 13.0,
    employees: "70,000",
    growth: "+4.5%",
    reputation: "87/100",
    details: "Global vaccine developer specializing in infectious diseases and HIV remedies.",
    news: "GSK receives priority validation for new shingles vaccine expansion.",
    ceo: "Emma Walmsley",
    founded: "2000",
    marketCap: "$78B",
    healthIndex: 87,
    status: "Verified Twin",
    suppliers: ["Lonza Group", "West Pharmaceutics"],
    competitors: ["AstraZeneca", "Sanofi SA"],
    customers: ["Healthcare Centers"]
  },
  {
    name: "Bristol Myers Squibb",
    industry: "Healthcare",
    city: "Princeton",
    country: "USA",
    coords: [40.357, -74.667],
    website: "https://bms.com",
    revenue: "$46B",
    risk: 18.2,
    employees: "34,000",
    growth: "-1.2%",
    reputation: "83/100",
    details: "Specialized biopharmaceutical developer focused on immunology and cardiovascular health.",
    news: "BMS gets expanded indication approval for cell therapy manufacturing site.",
    ceo: "Christopher Boerner",
    founded: "1887",
    marketCap: "$98B",
    healthIndex: 83,
    status: "Verified Twin",
    suppliers: ["Lonza Group"],
    competitors: ["Merck & Co.", "Pfizer Inc."],
    customers: ["Healthcare Centers"]
  },
  {
    name: "Sanofi SA",
    industry: "Healthcare",
    city: "Paris",
    country: "France",
    coords: [48.877, 2.308],
    website: "https://sanofi.com",
    revenue: "$47B",
    risk: 11.8,
    employees: "91,000",
    growth: "+3.8%",
    reputation: "89/100",
    details: "French healthcare champion offering global vaccine supply and immunology solutions.",
    news: "Sanofi announces $1.2B biotech facility upgrade in Lyon to scale antibody pipelines.",
    ceo: "Paul Hudson",
    founded: "2004",
    marketCap: "$118B",
    healthIndex: 89,
    status: "Verified Twin",
    suppliers: ["Siegfried Holding"],
    competitors: ["GSK plc", "Roche Group"],
    customers: ["Healthcare Centers"]
  },

  // 21-30: Finance
  {
    name: "JP Morgan Chase",
    industry: "Finance",
    city: "New York",
    country: "USA",
    coords: [40.756, -73.978],
    website: "https://jpmorganchase.com",
    revenue: "$158B",
    risk: 9.2,
    employees: "310,000",
    growth: "+11.4%",
    reputation: "93/100",
    details: "Largest global investment bank and custodian clearing global capital transactions.",
    news: "JP Morgan launches digital twin analytics engine for treasury clients.",
    ceo: "Jamie Dimon",
    founded: "1799",
    marketCap: "$560B",
    healthIndex: 93,
    status: "Verified Twin",
    suppliers: ["Microsoft Corporation", "Google Cloud"],
    competitors: ["Bank of America", "Goldman Sachs"],
    partners: ["Federal Reserve"],
    customers: ["Enterprise Clients", "Retail Investors"]
  },
  {
    name: "Bank of America",
    industry: "Finance",
    city: "Charlotte",
    country: "USA",
    coords: [35.227, -80.843],
    website: "https://bankofamerica.com",
    revenue: "$98B",
    risk: 11.4,
    employees: "213,000",
    growth: "+5.1%",
    reputation: "89/100",
    details: "Consumer banking giant offering commercial lending and advisory underwriting services.",
    news: "BofA logs record $8B digital retail channel volume in Q2 transaction reports.",
    ceo: "Brian Moynihan",
    founded: "1904",
    marketCap: "$280B",
    healthIndex: 89,
    status: "Verified Twin",
    suppliers: ["Microsoft Corporation"],
    competitors: ["JP Morgan Chase", "Citigroup"],
    customers: ["Retail Investors", "Enterprise Clients"]
  },
  {
    name: "Goldman Sachs",
    industry: "Finance",
    city: "New York",
    country: "USA",
    coords: [40.715, -74.014],
    website: "https://goldmansachs.com",
    revenue: "$46B",
    risk: 15.6,
    employees: "45,000",
    growth: "+8.2%",
    reputation: "86/100",
    details: "Global investment banking, asset management, and securities transaction broker.",
    news: "Goldman Sachs launches programmatic private credit tokenization infrastructure.",
    ceo: "David Solomon",
    founded: "1869",
    marketCap: "$138B",
    healthIndex: 86,
    status: "Verified Twin",
    suppliers: ["AWS Services"],
    competitors: ["Morgan Stanley", "JP Morgan Chase"],
    customers: ["Enterprise Clients"]
  },
  {
    name: "Morgan Stanley",
    industry: "Finance",
    city: "New York",
    country: "USA",
    coords: [40.760, -73.984],
    website: "https://morganstanley.com",
    revenue: "$54B",
    risk: 10.8,
    employees: "80,000",
    growth: "+6.8%",
    reputation: "88/100",
    details: "Global wealth manager, institutional advisor, and capital markets underwriter.",
    news: "Morgan Stanley adds generative AI broker assistance systems for wealth advisory.",
    ceo: "Ted Pick",
    founded: "1935",
    marketCap: "$152B",
    healthIndex: 88,
    status: "Verified Twin",
    suppliers: ["Microsoft Corporation"],
    competitors: ["Goldman Sachs", "JP Morgan Chase"],
    customers: ["High-Net-Worth Individuals"]
  },
  {
    name: "HSBC Holdings",
    industry: "Finance",
    city: "London",
    country: "UK",
    coords: [51.507, -0.127],
    website: "https://hsbc.com",
    revenue: "$66B",
    risk: 14.2,
    employees: "220,000",
    growth: "+4.8%",
    reputation: "85/100",
    details: "Europe's largest bank linking Asia trade corridors via commercial settlements.",
    news: "HSBC expands trade finance blockchain pipelines across Southeast Asia sea routes.",
    ceo: "Georges Elhedery",
    founded: "1865",
    marketCap: "$162B",
    healthIndex: 85,
    status: "Verified Twin",
    suppliers: ["Sino Logistics", "Google Cloud"],
    competitors: ["Barclays Bank", "Standard Chartered"],
    customers: ["Enterprise Clients"]
  },
  {
    name: "Allianz SE",
    industry: "Finance",
    city: "Munich",
    country: "Germany",
    coords: [48.135, 11.582],
    website: "https://allianz.com",
    revenue: "$161B",
    risk: 8.2,
    employees: "159,000",
    growth: "+5.6%",
    reputation: "92/100",
    details: "Global asset manager and insurance giant underwriting supply line risks.",
    news: "Allianz launches customized supply disruption policy models for manufacturing partners.",
    ceo: "Oliver Bäte",
    founded: "1890",
    marketCap: "$110B",
    healthIndex: 92,
    status: "Verified Twin",
    suppliers: ["Microsoft Corporation"],
    competitors: ["AXA Group", "Munich Re"],
    customers: ["Enterprise Clients"]
  },
  {
    name: "Citigroup Inc.",
    industry: "Finance",
    city: "New York",
    country: "USA",
    coords: [40.725, -74.011],
    website: "https://citi.com",
    revenue: "$78B",
    risk: 16.5,
    employees: "240,000",
    growth: "+2.1%",
    reputation: "82/100",
    details: "Global banking franchise clearing transactional balances across 100+ countries.",
    news: "Citigroup structures multi-currency cash pool infrastructure for retail platforms.",
    ceo: "Jane Fraser",
    founded: "1812",
    marketCap: "$118B",
    healthIndex: 82,
    status: "Verified Twin",
    suppliers: ["AWS Services"],
    competitors: ["JP Morgan Chase", "Bank of America"],
    customers: ["Enterprise Clients"]
  },
  {
    name: "BNP Paribas",
    industry: "Finance",
    city: "Paris",
    country: "France",
    coords: [48.872, 2.332],
    website: "https://bnpparibas.com",
    revenue: "$50B",
    risk: 11.2,
    employees: "190,000",
    growth: "+4.1%",
    reputation: "89/100",
    details: "French banking leader offering European corporate asset finance products.",
    news: "BNP Paribas expands green bond issuing capacity for utility infrastructure projects.",
    ceo: "Jean-Laurent Bonnafé",
    founded: "1848",
    marketCap: "$78B",
    healthIndex: 89,
    status: "Verified Twin",
    suppliers: ["IBM Cloud"],
    competitors: ["Societe Generale", "Deutsche Bank"],
    customers: ["Enterprise Clients"]
  },
  {
    name: "Barclays Bank",
    industry: "Finance",
    city: "London",
    country: "UK",
    coords: [51.503, -0.019],
    website: "https://barclays.com",
    revenue: "$32B",
    risk: 15.0,
    employees: "90,000",
    growth: "+3.1%",
    reputation: "84/100",
    details: "British multinational universal bank handling retail and wholesale financing.",
    news: "Barclays launches specialized carbon transaction advisory services for transport firms.",
    ceo: "C.S. Venkatakrishnan",
    founded: "1690",
    marketCap: "$42B",
    healthIndex: 84,
    status: "Verified Twin",
    suppliers: ["Microsoft Corporation"],
    competitors: ["HSBC Holdings", "Lloyds Banking Group"],
    customers: ["Retail Investors", "Enterprise Clients"]
  },
  {
    name: "UBS Group AG",
    industry: "Finance",
    city: "Zurich",
    country: "Switzerland",
    coords: [47.370, 8.539],
    website: "https://ubs.com",
    revenue: "$40B",
    risk: 13.8,
    employees: "120,000",
    growth: "+18.2%",
    reputation: "88/100",
    details: "The largest Swiss banking institution and global wealth manager.",
    news: "UBS completes operational integration of former Credit Suisse assets.",
    ceo: "Sergio Ermotti",
    founded: "1862",
    marketCap: "$88B",
    healthIndex: 88,
    status: "Verified Twin",
    suppliers: ["Google Cloud"],
    competitors: ["Morgan Stanley", "Julius Baer"],
    customers: ["High-Net-Worth Individuals"]
  },

  // 31-40: Manufacturing & Energy
  {
    name: "Siemens AG",
    industry: "Manufacturing",
    city: "Munich",
    country: "Germany",
    coords: [48.135, 11.582],
    website: "https://siemens.com",
    revenue: "$85B",
    risk: 10.2,
    employees: "311,000",
    growth: "+8.2%",
    reputation: "92/100",
    details: "Industrial automation, grid infrastructures, and smart factory builder.",
    news: "Siemens deploys generative AI integrations across factory controls pipelines.",
    ceo: "Roland Busch",
    founded: "1847",
    marketCap: "$152B",
    healthIndex: 92,
    status: "Verified Twin",
    suppliers: ["ASML Semiconductors", "Sino Logistics"],
    competitors: ["General Electric", "ABB Ltd."],
    partners: ["Infosys Ltd."],
    customers: ["ExxonMobil", "Gigafactory Berlin"],
    factories: ["Munich Automations Plant"]
  },
  {
    name: "General Electric",
    industry: "Manufacturing",
    city: "Boston",
    country: "USA",
    coords: [42.360, -71.058],
    website: "https://ge.com",
    revenue: "$68B",
    risk: 15.6,
    employees: "125,000",
    growth: "+4.5%",
    reputation: "85/100",
    details: "Aerospace power turbine developer pushing green aviation options.",
    news: "GE Aerospace secures $2B contract for advanced hybrid jet propulsion turbines.",
    ceo: "H. Lawrence Culp Jr.",
    founded: "1892",
    marketCap: "$180B",
    healthIndex: 85,
    status: "Verified Twin",
    suppliers: ["Apex Mining", "Sino Logistics"],
    competitors: ["Siemens AG", "Rolls-Royce plc"],
    customers: ["Boeing Co.", "Airbus SAS"],
    factories: ["Cincinnati Turbine Works"]
  },
  {
    name: "Boeing Co.",
    industry: "Manufacturing",
    city: "Arlington",
    country: "USA",
    coords: [38.879, -77.086],
    website: "https://boeing.com",
    revenue: "$78B",
    risk: 32.5,
    employees: "156,000",
    growth: "-5.2%",
    reputation: "71/100",
    details: "Global aerospace giant designing commercial jets and defense products.",
    news: "Boeing ramps quality inspection metrics across assembly points.",
    ceo: "Kelly Ortberg",
    founded: "1916",
    marketCap: "$110B",
    healthIndex: 71,
    status: "Verified Twin",
    suppliers: ["General Electric", "Sino Logistics", "Arconic Corp"],
    competitors: ["Airbus SAS"],
    customers: ["London Heathrow", "Singapore Airlines"],
    factories: ["Everett Final Assembly"]
  },
  {
    name: "Airbus SAS",
    industry: "Manufacturing",
    city: "Toulouse",
    country: "France",
    coords: [43.604, 1.444],
    website: "https://airbus.com",
    revenue: "$65B",
    risk: 13.0,
    employees: "134,000",
    growth: "+8.4%",
    reputation: "90/100",
    details: "European aerospace champion manufacturing fuel-efficient commercial aircraft.",
    news: "Airbus delivers record 73 commercial aircraft in monthly regional shipments.",
    ceo: "Guillaume Faury",
    founded: "1970",
    marketCap: "$118B",
    healthIndex: 90,
    status: "Verified Twin",
    suppliers: ["General Electric", "Sino Logistics", "Safran Group"],
    competitors: ["Boeing Co."],
    customers: ["London Heathrow", "Air France"],
    factories: ["Toulouse Assembly Hall"]
  },
  {
    name: "ExxonMobil",
    industry: "Energy",
    city: "Spring",
    country: "USA",
    coords: [30.082, -95.421],
    website: "https://exxonmobil.com",
    revenue: "$344B",
    risk: 18.5,
    employees: "62,000",
    growth: "-2.5%",
    reputation: "78/100",
    details: "Supermajor oil and gas producer investing in carbon capture projects.",
    news: "ExxonMobil completes purchase of shale fields to expand drilling capacity.",
    ceo: "Darren Woods",
    founded: "1882",
    marketCap: "$480B",
    healthIndex: 78,
    status: "Verified Twin",
    suppliers: ["Sino Logistics", "Caterpillar Inc."],
    competitors: ["Chevron Corp", "Shell plc"],
    customers: ["Client Consumers", "Siemens AG"]
  },
  {
    name: "Chevron Corp",
    industry: "Energy",
    city: "San Ramon",
    country: "USA",
    coords: [37.779, -121.978],
    website: "https://chevron.com",
    revenue: "$200B",
    risk: 16.8,
    employees: "43,000",
    growth: "-1.8%",
    reputation: "80/100",
    details: "Global energy provider active in geothermal and hydrogen projects.",
    news: "Chevron initiates commercial solar power arrays for refinery facilities.",
    ceo: "Mike Wirth",
    founded: "1879",
    marketCap: "$298B",
    healthIndex: 80,
    status: "Verified Twin",
    suppliers: ["Sino Logistics"],
    competitors: ["ExxonMobil", "BP plc"],
    customers: ["Client Consumers"]
  },
  {
    name: "Shell plc",
    industry: "Energy",
    city: "London",
    country: "UK",
    coords: [51.507, -0.127],
    website: "https://shell.com",
    revenue: "$316B",
    risk: 15.0,
    employees: "90,000",
    growth: "+1.2%",
    reputation: "82/100",
    details: "Anglo-Dutch supermajor scaling global LNG transport hubs.",
    news: "Shell signs long-term LNG deliveries pipeline deal with European utilities.",
    ceo: "Wael Sawan",
    founded: "1907",
    marketCap: "$210B",
    healthIndex: 82,
    status: "Verified Twin",
    suppliers: ["Sino Logistics"],
    competitors: ["ExxonMobil", "TotalEnergies"],
    customers: ["Client Consumers"]
  },
  {
    name: "BP plc",
    industry: "Energy",
    city: "London",
    country: "UK",
    coords: [51.509, -0.134],
    website: "https://bp.com",
    revenue: "$210B",
    risk: 17.2,
    employees: "87,000",
    growth: "-3.1%",
    reputation: "79/100",
    details: "Integrated energy giant building fast electric charging networks.",
    news: "BP increases investment in offshore wind power arrays near the UK.",
    ceo: "Murray Auchincloss",
    founded: "1909",
    marketCap: "$110B",
    healthIndex: 79,
    status: "Verified Twin",
    suppliers: ["Sino Logistics"],
    competitors: ["Chevron Corp", "Shell plc"],
    customers: ["Client Consumers"]
  },
  {
    name: "Saudi Aramco",
    industry: "Energy",
    city: "Dhahran",
    country: "Saudi Arabia",
    coords: [26.284, 50.111],
    website: "https://aramco.com",
    revenue: "$494B",
    risk: 12.0,
    employees: "70,000",
    growth: "+6.8%",
    reputation: "85/100",
    details: "The world's largest corporate oil exporter managing giant reservoirs.",
    news: "Aramco reports record net income and expands pipeline capacity.",
    ceo: "Amin H. Nasser",
    founded: "1933",
    marketCap: "$1.98T",
    healthIndex: 85,
    status: "Verified Twin",
    suppliers: ["Sino Logistics", "Baker Hughes"],
    competitors: ["ExxonMobil", "Chevron Corp"],
    customers: ["Refinery Clients"]
  },
  {
    name: "TotalEnergies",
    industry: "Energy",
    city: "Courbevoie",
    country: "France",
    coords: [48.892, 2.243],
    website: "https://totalenergies.com",
    revenue: "$218B",
    risk: 13.8,
    employees: "100,000",
    growth: "+4.1%",
    reputation: "84/100",
    details: "Broad energy developer expanding wind and solar portfolios.",
    news: "TotalEnergies wins major offshore wind project bidding in New York.",
    ceo: "Patrick Pouyanné",
    founded: "1924",
    marketCap: "$145B",
    healthIndex: 84,
    status: "Verified Twin",
    suppliers: ["Sino Logistics"],
    competitors: ["Shell plc", "BP plc"],
    customers: ["Client Consumers"]
  },

  // 41-50: Logistics & Retail
  {
    name: "Sino Logistics",
    industry: "Logistics",
    city: "Singapore",
    country: "Singapore",
    coords: [1.352, 103.820],
    website: "https://sinolog.sg",
    revenue: "$850M",
    risk: 18.9,
    employees: "4,200",
    growth: "+12.4%",
    reputation: "91/100",
    details: "Container shipping line coordinating global sea-freight channels.",
    news: "Singapore automated sorting facility expands processing capacity.",
    ceo: "Alan Wong",
    founded: "2010",
    marketCap: "$4.5B",
    healthIndex: 91,
    status: "Verified Twin",
    suppliers: ["Port of Shanghai", "Port of Rotterdam"],
    competitors: ["DHL Supply Chain", "FedEx Express", "Maersk Line"],
    partners: ["Changi Airport Hub"],
    customers: ["Apple Inc.", "Tesla Motors", "ExxonMobil"],
    ports: ["Port of Rotterdam"]
  },
  {
    name: "DHL Supply Chain",
    industry: "Logistics",
    city: "Bonn",
    country: "Germany",
    coords: [50.733, 7.100],
    website: "https://dhl.com",
    revenue: "$88B",
    risk: 10.2,
    employees: "380,000",
    growth: "+6.8%",
    reputation: "92/100",
    details: "Global contract logistics manager offering advanced warehouse automation.",
    news: "DHL deploys automated picking robots inside 50 main hubs.",
    ceo: "Tobias Meyer",
    founded: "1969",
    marketCap: "$58B",
    healthIndex: 92,
    status: "Verified Twin",
    suppliers: ["London Heathrow", "Maersk Line"],
    competitors: ["FedEx Express", "UPS Logistics"],
    customers: ["Apple Inc.", "Siemens AG"],
    warehouses: ["Chicago Distribution Hub"]
  },
  {
    name: "FedEx Express",
    industry: "Logistics",
    city: "Memphis",
    country: "USA",
    coords: [35.149, -90.048],
    website: "https://fedex.com",
    revenue: "$90B",
    risk: 13.5,
    employees: "520,000",
    growth: "+3.5%",
    reputation: "88/100",
    details: "Express overnight courier services using a massive cargo plane fleet.",
    news: "FedEx completes cargo container sorting facility upgrades in Memphis.",
    ceo: "Raj Subramaniam",
    founded: "1971",
    marketCap: "$62B",
    healthIndex: 88,
    status: "Verified Twin",
    suppliers: ["Boeing Co.", "London Heathrow"],
    competitors: ["DHL Supply Chain", "UPS Logistics"],
    customers: ["Client Consumers"]
  },
  {
    name: "UPS Logistics",
    industry: "Logistics",
    city: "Atlanta",
    country: "USA",
    coords: [33.749, -84.388],
    website: "https://ups.com",
    revenue: "$93B",
    risk: 11.2,
    employees: "500,000",
    growth: "+2.8%",
    reputation: "89/100",
    details: "Global package delivery firm scaling low-emission vehicle fleets.",
    news: "UPS places orders for alternative fuel delivery vans.",
    ceo: "Carol Tomé",
    founded: "1907",
    marketCap: "$130B",
    healthIndex: 89,
    status: "Verified Twin",
    suppliers: ["Boeing Co."],
    competitors: ["DHL Supply Chain", "FedEx Express"],
    customers: ["Client Consumers"]
  },
  {
    name: "Maersk Line",
    industry: "Logistics",
    city: "Copenhagen",
    country: "Denmark",
    coords: [55.676, 12.568],
    website: "https://maersk.com",
    revenue: "$80B",
    risk: 19.5,
    employees: "110,000",
    growth: "+14.5%",
    reputation: "90/100",
    details: "Ocean shipping leader retrofitting ships to run on green methanol.",
    news: "Maersk orders dual-fuel container vessels for Asia routes.",
    ceo: "Vincent Clerc",
    founded: "1904",
    marketCap: "$38B",
    healthIndex: 90,
    status: "Verified Twin",
    suppliers: ["Port of LA", "Port of Rotterdam"],
    competitors: ["Sino Logistics", "Hapag-Lloyd"],
    customers: ["Walmart Stores", "Amazon Retail"],
    ports: ["Port of LA"]
  },
  {
    name: "Walmart Stores",
    industry: "Retail",
    city: "Bentonville",
    country: "USA",
    coords: [36.372, -94.208],
    website: "https://walmart.com",
    revenue: "$611B",
    risk: 8.5,
    employees: "2,100,000",
    growth: "+4.2%",
    reputation: "89/100",
    details: "The largest global physical retailer operating deep discount supercenters.",
    news: "Walmart expands direct grocery deliveries to cover US suburban zones.",
    ceo: "Doug McMillon",
    founded: "1962",
    marketCap: "$420B",
    healthIndex: 89,
    status: "Verified Twin",
    suppliers: ["Maersk Line", "British Farms Co", "Sino Logistics"],
    competitors: ["Amazon Retail", "Costco Wholesale"],
    customers: ["Client Consumers"],
    warehouses: ["Bentonville Distribution Center"]
  },
  {
    name: "Amazon Retail",
    industry: "Retail",
    city: "Seattle",
    country: "USA",
    coords: [47.609, -122.333],
    website: "https://amazon.com",
    revenue: "$574B",
    risk: 9.8,
    employees: "1,540,000",
    growth: "+11.8%",
    reputation: "92/100",
    details: "E-commerce leader managing advanced robot fulfillment lines.",
    news: "Amazon launches generative assistant for product listing updates.",
    ceo: "Andy Jassy",
    founded: "1994",
    marketCap: "$1.85T",
    healthIndex: 92,
    status: "Verified Twin",
    suppliers: ["Maersk Line", "UPS Logistics"],
    competitors: ["Walmart Stores", "Google LLC"],
    customers: ["Client Consumers"],
    warehouses: ["Chicago Distribution Hub"]
  },
  {
    name: "Costco Wholesale",
    industry: "Retail",
    city: "Issaquah",
    country: "USA",
    coords: [47.530, -122.032],
    website: "https://costco.com",
    revenue: "$242B",
    risk: 7.8,
    employees: "304,000",
    growth: "+7.2%",
    reputation: "94/100",
    details: "Membership-only warehouse club retail chain offering wholesale prices.",
    news: "Costco opens new membership centers in Spain and Germany.",
    ceo: "Ron Vachris",
    founded: "1983",
    marketCap: "$310B",
    healthIndex: 94,
    status: "Verified Twin",
    suppliers: ["British Farms Co", "UPS Logistics"],
    competitors: ["Walmart Stores", "Target Brands"],
    customers: ["Client Consumers"]
  },
  {
    name: "IKEA International",
    industry: "Retail",
    city: "Älmhult",
    country: "Sweden",
    coords: [56.550, 14.135],
    website: "https://ikea.com",
    revenue: "$47B",
    risk: 11.2,
    employees: "230,000",
    growth: "+3.5%",
    reputation: "91/100",
    details: "Swedish flat-pack furniture manufacturer expanding city center formats.",
    news: "IKEA commits $2.2B to expand retail store presence in USA markets.",
    ceo: "Jesper Brodin",
    founded: "1943",
    marketCap: "$62B",
    healthIndex: 91,
    status: "Verified Twin",
    suppliers: ["Sino Logistics"],
    competitors: ["Wayfair LLC"],
    customers: ["Client Consumers"]
  },
  {
    name: "Decathlon Group",
    industry: "Retail",
    city: "Lille",
    country: "France",
    coords: [50.629, 3.057],
    website: "https://decathlon.com",
    revenue: "$16B",
    risk: 9.5,
    employees: "105,000",
    growth: "+5.8%",
    reputation: "90/100",
    details: "The largest global sporting goods retailer designing affordable equipment.",
    news: "Decathlon announces circular product rental models across Europe hubs.",
    ceo: "Barbara Martin Coppola",
    founded: "1976",
    marketCap: "$12B",
    healthIndex: 90,
    status: "Verified Twin",
    suppliers: ["Sino Logistics"],
    competitors: ["Nike Inc.", "Adidas AG"],
    customers: ["Client Consumers"]
  },

  // 51-60: Infrastructures, Warehouses, Ports, Airports, Offices
  {
    name: "Port of Shanghai",
    industry: "Logistics",
    city: "Shanghai",
    country: "China",
    coords: [30.624, 122.062],
    website: "https://portshanghai.com.cn",
    revenue: "$5.8B",
    risk: 22.0,
    employees: "24,000",
    growth: "+8.4%",
    reputation: "90/100",
    details: "The busiest container port on Earth managing high-volume global outbound sea freight.",
    news: "Shanghai port reaches record high TEU throughput during export peak season.",
    ceo: "Gu Jinshan",
    founded: "2003",
    marketCap: "$14B",
    healthIndex: 90,
    status: "Verified Twin",
    type: "port"
  },
  {
    name: "Port of Rotterdam",
    industry: "Logistics",
    city: "Rotterdam",
    country: "Netherlands",
    coords: [51.948, 4.142],
    website: "https://portofrotterdam.com",
    revenue: "$950M",
    risk: 15.2,
    employees: "1,200",
    growth: "+3.2%",
    reputation: "93/100",
    details: "The largest seaport in Europe serving as a gateway to Germany and central EU regions.",
    news: "Rotterdam begins construction on deep-water clean hydrogen import docks.",
    ceo: "Boudewijn Siemons",
    founded: "1932",
    marketCap: "N/A",
    healthIndex: 93,
    status: "Verified Twin",
    type: "port"
  },
  {
    name: "Port of LA",
    industry: "Logistics",
    city: "Los Angeles",
    country: "USA",
    coords: [33.743, -118.267],
    website: "https://portofla.org",
    revenue: "$610M",
    risk: 18.9,
    employees: "1,100",
    growth: "+4.5%",
    reputation: "89/100",
    details: "The premier seaport in North America handling billions of dollars in trans-Pacific trade.",
    news: "LA port launches clean air initiative for all container loading trucks.",
    ceo: "Gene Seroka",
    founded: "1907",
    marketCap: "N/A",
    healthIndex: 89,
    status: "Verified Twin",
    type: "port"
  },
  {
    name: "London Heathrow",
    industry: "Logistics",
    city: "London",
    country: "UK",
    coords: [51.470, -0.454],
    website: "https://heathrow.com",
    revenue: "$3.5B",
    risk: 12.0,
    employees: "76,000",
    growth: "+14.8%",
    reputation: "91/100",
    details: "Primary international aviation hub in Europe handling express global cargo air shipments.",
    news: "Heathrow airport expands automated luggage and cargo routing networks.",
    ceo: "Thomas Woldbye",
    founded: "1946",
    marketCap: "$8B",
    healthIndex: 91,
    status: "Verified Twin",
    type: "airport"
  },
  {
    name: "Tokyo Haneda",
    industry: "Logistics",
    city: "Tokyo",
    country: "Japan",
    coords: [35.549, 139.779],
    website: "https://tokyo-airport-bldg.co.jp",
    revenue: "$2.1B",
    risk: 8.5,
    employees: "12,000",
    growth: "+9.2%",
    reputation: "96/100",
    details: "Highly efficient Asian aviation hub supporting key tech shipment transit corridors.",
    news: "Haneda ranks as the most punctual mega-airport globally for the third year running.",
    ceo: "Nobuaki Yokoyama",
    founded: "1931",
    marketCap: "$5B",
    healthIndex: 96,
    status: "Verified Twin",
    type: "airport"
  },
  {
    name: "Foxconn Shenzhen",
    industry: "Manufacturing",
    city: "Shenzhen",
    country: "China",
    coords: [22.653, 114.037],
    website: "https://foxconn.com",
    revenue: "$130B",
    risk: 26.5,
    employees: "450,000",
    growth: "+5.4%",
    reputation: "82/100",
    details: "Huge electronic components assembly complex and main manufacturer of premium consumer smartphones.",
    news: "Shenzhen site rolls out automated dry-lab quality inspection lines.",
    ceo: "Young Liu",
    founded: "1974",
    marketCap: "$42B",
    healthIndex: 82,
    status: "Verified Twin",
    type: "factory"
  },
  {
    name: "Gigafactory Berlin",
    industry: "Manufacturing",
    city: "Grünheide",
    country: "Germany",
    coords: [52.390, 13.790],
    website: "https://tesla.com/gigafactory-berlin",
    revenue: "$8.4B",
    risk: 14.2,
    employees: "12,000",
    growth: "+32.5%",
    reputation: "88/100",
    details: "Advanced electric vehicle stamping, battery cell casing, and final assembly hub.",
    news: "Berlin site expands output capacity targeting 10k vehicles per week.",
    ceo: "Elon Musk",
    founded: "2019",
    marketCap: "N/A",
    healthIndex: 88,
    status: "Verified Twin",
    type: "factory"
  },
  {
    name: "Chicago Distribution Hub",
    industry: "Logistics",
    city: "Chicago",
    country: "USA",
    coords: [41.878, -87.629],
    website: "https://dhl.com",
    revenue: "N/A",
    risk: 10.5,
    employees: "450",
    growth: "+2.8%",
    reputation: "90/100",
    details: "Hyperscale automated logistics warehouse with 50 automated guide vehicle systems.",
    news: "Chicago hub achieves 100% sorting automation for high-priority packages.",
    ceo: "Tobias Meyer",
    founded: "2015",
    marketCap: "N/A",
    healthIndex: 90,
    status: "Verified Twin",
    type: "warehouse"
  },
  {
    name: "British Farms Co",
    industry: "Food & Beverage",
    city: "Lincoln",
    country: "UK",
    coords: [53.227, -0.537],
    website: "https://britishfarms.co.uk",
    revenue: "$45M",
    risk: 28.5,
    employees: "120",
    growth: "+2.1%",
    reputation: "84/100",
    details: "Cooperative agricultural producer supplying raw ingredients to regional food networks.",
    news: "British Farms launches sustainable electric tractor fleet for harvesting operations.",
    ceo: "John Harrison",
    founded: "1994",
    marketCap: "N/A",
    healthIndex: 84,
    status: "Verified Twin",
    type: "office"
  },
  {
    name: "Apple London Office",
    industry: "Technology",
    city: "London",
    country: "UK",
    coords: [51.513, -0.142],
    website: "https://apple.com/uk",
    revenue: "N/A",
    risk: 5.0,
    employees: "2,400",
    growth: "+5.4%",
    reputation: "95/100",
    details: "Regional headquarters handling corporate operations, hardware sales, and UK retail assets.",
    news: "Apple moves UK team into newly restored Battersea Power Station HQ.",
    ceo: "Tim Cook",
    founded: "2023",
    marketCap: "N/A",
    healthIndex: 95,
    status: "Verified Twin",
    type: "office"
  }
];
